aws_region                                  = "us-east-1"
kube_version                                = "1.26"
subnet_azs                                  = ["us-east-1a", "us-east-1b", "us-east-1c", "us-east-1d"]
cidr_block_vpc                              = "10.0.0.0/16"
cidr_public_subnet                          = ["10.0.3.0/24", "10.0.4.0/24"]
cidr_privite_subnet                         = ["10.0.5.0/24", "10.0.6.0/24"]
bootstrap_cluster_creator_admin_permissions = false
ami_type                                    = "AL2_x86_64"
instance_type_node                          = "t2micro"
disk_size_node                              = "40"
volume_size_ec2_nodes                       = "40"
max_unavailable_node                        = "1"
name                                        = "app_eks"
cluster_name                                = "fusions"
app_name                                    = "addressbook"
env                                         = "prod"
subnet_ids                                  = ["10.0.3.0/24", "10.0.4.0/24"] # if its public select cidr_public_subnet or if its private select cidr_privite_subnet 
image_id_for_node                           = "AL2_x86_64"
#key_ec2_templete =
desired_size = 2
min_size     = 2
max_size     = 4
create       = "true"
